"""updated Known moons

Revision ID: 2391ae7d2862
Revises: 5a945492da0f
Create Date: 2022-11-02 14:35:17.024767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2391ae7d2862'
down_revision = '5a945492da0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('known_moons', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planet', 'known_moons')
    # ### end Alembic commands ###
